### ISSUE TITLE
Building on arm64

### ISSUE THREAD

**Issue by codesian** [pistacheio/pistache#251]
Im triying to run some samples on an aarch64, but seems theres a problem on memset. Examples works perfect on other arch we tested (x86, x64...). This is a basic gdb backtrace:

```
(gdb) run
Starting program: /home/nvidia/Desktop/install/pistache/build/examples/run_http_server 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".
Cores = 4
Using 2 threads
[New Thread 0x7fb7be31e0 (LWP 7945)]
[New Thread 0x7fb73e31e0 (LWP 7946)]

Thread 3 "run_http_server" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fb73e31e0 (LWP 7946)]
memset () at ../sysdeps/aarch64/memset.S:212
212		dc	zva, dst
(gdb) bt
#0  memset () at ../sysdeps/aarch64/memset.S:212
#1  0x00000000004476ec in Pistache::Tcp::Transport::handleIncoming(std::shared_ptr<Pistache::Tcp::Peer> const&) ()
#2  0x000000000044bf0c in Pistache::Tcp::Transport::onReady(Pistache::Aio::FdSet const&) ()
#3  0x000000000045442c in Pistache::Aio::SyncImpl::runOnce() ()
#4  0x0000000000451f84 in std::thread::_Impl<std::_Bind_simple<Pistache::Aio::AsyncImpl::Worker::run()::{lambda()#1} ()> >::_M_run() ()
#5  0x0000007fb7eb1280 in ?? () from /usr/lib/aarch64-linux-gnu/libstdc++.so.6
#6  0x0000007fb7f8efc4 in start_thread (arg=0x7fb7eb1260) at pthread_create.c:335
#7  0x0000007fb7d572e0 in thread_start () at ../sysdeps/unix/sysv/linux/aarch64/clone.S:89
```

Build system:

```
nvidia@tegra:~/Desktop/install/pistache/build/examples$ uname -a
Linux Tegra 4.4.38-tegra #1 SMP PREEMPT Thu May 17 00:15:19 PDT 2018 aarch64 aarch64 aarch64 GNU/Linux
```

Library versions:

```
ldd (Ubuntu GLIBC 2.23-0ubuntu10) 2.23
linux-vdso.so.1 =>  (0x0000007f818a2000)
	libpthread.so.0 => /lib/aarch64-linux-gnu/libpthread.so.0 (0x0000007f81856000)
	libstdc++.so.6 => /usr/lib/aarch64-linux-gnu/libstdc++.so.6 (0x0000007f816c7000)
	libgcc_s.so.1 => /lib/aarch64-linux-gnu/libgcc_s.so.1 (0x0000007f816a6000)
	libc.so.6 => /lib/aarch64-linux-gnu/libc.so.6 (0x0000007f8155e000)
	/lib/ld-linux-aarch64.so.1 (0x000000557cbd1000)
	libm.so.6 => /lib/aarch64-linux-gnu/libm.so.6 (0x0000007f814b1000)
```

Can anyone help me please?
Thanks

**Comment by hydratim** [comment]
Hi, 
Is this still a problem or does it now compile for aarch64? I'd test it, but I don't have a suitible ARM based system to test it on.

Thanks
